import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";


const interTight = Inter_Tight({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], 
  subsets: ["latin"], 
  variable: "--font-inter-tight",
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}